blue_hexcode='#3F51B5'
orange_hexcode='#FF5722'
pink_hexcode='#FF4081'
assert_message_invalid_login='Enter a valid email or phone number'
path = "/home/ankit_kumar/PycharmProjects/Selenium_automation/data/test_data.csv"
invalid_cred_path="/home/ankit_kumar/PycharmProjects/Selenium_automation/data/test_data_invalid_cedentials.csv"
assert_date_format="%a, %b %d"
six_hours='6'
two_hours='2'
eight_hours='8'
description='testing from testcase'
delete_message="No Time Entries. Use the form below to add one."
shared_with_username='ashish'
test_username='hiwaytest@hashedin.com'
test_password='Hiway@123'
google_url='https://www.google.com/'
test_userID_name='hiwaytest'
my_name='ankit'
specified_date="Mon, Feb 18"
freeze_message='Timesheet older than 2 or more days cannot be updated. Contact your reporting manager for assistance.'
ten_hours='10'
total_hrs_msg='Total Hours cannot exceed 24.'
fifteen_hours='15'
edit_type="Finance"
edit_hours='9'
edit_mins='7'
edit_description='updated description'
hiway_user_name='hiwaytest'
