blue_hexcode='#3F51B5'
orange_hexcode='#FF5722'
pink_hexcode='#FF4081'
assert_message_invalid_login='Enter a valid email or phone number'
path = "/home/ankit_kumar/PycharmProjects/Selenium_automation/data/test_data.csv"
invalid_cred_path="/home/ankit_kumar/PycharmProjects/Selenium_automation/data/test_data_invalid_cedentials.csv"
assert_date_format="%a, %b %d"
six_hours='6'
two_hours='2'
eight_hours='8'
description='testing from testcase'
delete_message="No Time Entries. Use the form below to add one."
shared_with_username='ashish bhatt'